# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash

addons:
  apt:
    update: true
    packages: bzr-fastimport

script:
  - bzr branch lp:lightdm-gtk-greeter
  - cd lightdm-gtk-greeter
  - git init
  - bzr fast-export --plain . | git fast-import
  - git reset --hard HEAD
  - git remote add origin git@github.com:srcmirror/lightdm-gtk-greeter.git
  - git push origin --all
  - git push origin --tags
